[package]
name = "test4"
version = "0.1.0"
authors = ["red75prime <red75prim@gmail.com>"]

[dependencies]
rand = "0.3"
winapi = "0.2"
advapi32-sys = "0.2"
kernel32-sys = "0.2"
time = "*"

[profile.release]
#lto = true
